---
# Molecule configuration for security role
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml

driver:
  name: docker

platforms:
  - name: security-ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - "2222:22/tcp"

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../../
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer,yaml
  inventory:
    group_vars:
      all:
        ansible_user: root
        ssh_port: 1923
        fail2ban_maxretry: 5
        fail2ban_bantime: 3600
        firewall_allowed_tcp_ports:
          - "1923"
          - "80"
          - "443"
          - "8081"
        firewall_allowed_udp_ports:
          - "443"

verifier:
  name: testinfra
  options:
    v: 1

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
